
module.exports = {
	// Codes d’erreur « conviviaux »
	"500": "Aïe !",
	"erreurInterne": "Une erreur est survenue.",
	"membreInexistant": "Ce membre n’existe pas.",
	"organisationInexistante": "Cette organisation n’existe pas.",
	"serviceInexistant": "Ce service n’existe pas.",
	"offreInexistante": "Cette offre n’existe pas.",
	"renduVue": "Une erreur est survenue durant le rendu de cette page.",
	"gorille": "Cherchez‐vous le gorille échappé de sa cage ?",

	// Codes d’erreur des formulaires
	"ERREUR_NOM_UTILISATEUR": "Ce nom d’utilisateur est incorrect.",
	"ERREUR_STATUT": "Ce statut est incorrect.",
	"ERREUR_PRÉNOM": "Ce prénom est incorrect.",
	"ERREUR_NOM_PATRONYMIQUE": "Ce nom patronymique est incorrect.",
	"ERREUR_NOM_MARITAL": "Ce nom marital est incorrect.",
	"ERREUR_RAISON_SOCIALE": "Cette raison sociale est incorrecte.",
	"ERREUR_NOM": "Ce nom est incorrect.",
	"ERREUR_INTITULÉ": "Cet intitulé est incorrect.",
	"ERREUR_INTITULÉ_COURT": "Cet intitulé court est incorrect.",
	"ERREUR_INTITULÉ_COMPLET": "Cet intitulé complet est incorrect.",
	"ERREUR_CIVILITÉ": "Cette civilité est incorrecte.",
	"ERREUR_LIEN_SITE_PERSONNEL": "Ce lien de site personnel est incorrect.",
	"ERREUR_LIEN_SITE_PROFESSIONNEL": "Ce lien de site professionnel est incorrect.",
	"ERREUR_LIEN_LINKEDIN": "Ce lien vers une page LinkedIn est incorrect.",
	"ERREUR_LIEN_VIADEO": "Ce lien vers une page Viadeo est incorrect.",
	"ERREUR_ADRESSE_MÉL": "Cette adresse mél est incorrecte.",
	"ERREUR_NUMÉRO_TÉLÉPHONE": "Ce numéro de téléphone est incorrect.",
	"ERREUR_VILLE": "Cette ville est incorrecte.",
	"ERREUR_CODE_POSTAL": "Ce code postal est incorrect.",
	"ERREUR_PAYS": "Ce pays est incorrect.",
	"ERREUR_POSTE_ACTUEL": "Ce poste actuel est incorrect.",
	"ERREUR_TYPE_EMPLOI": "Ce type d’emploi est incorrect.",
	"ERREUR_EFFECTIF": "Cet effectif est incorrect.",
	"ERREUR_SECTEUR_ACTIVITÉ": "Ce secteur d’activité est incorrect.",
	"ERREUR_MOTIF": "Ce motif est incorrect.",
	"ERREUR_DESCRIPTION": "Cette description est incorrecte.",
	"ERREUR_ADRESSE": "Cette adresse est incorrecte.",
	"ERREUR_FORMAT": "Un fichier a un format incorrect.",
	"ERREUR_DOMAINE_MANQUANT": "Vous devez indiquer au moins un domaine.",

	"ERREUR_DATE": "Cette date est incorrecte.",
	"ERREUR_PÉRIODE": "Cette période est incorrecte.",
	"ERREUR_DURÉE_PÉRIODE": "Cette période est plus courte que la durée prévue indiquée.",
	"ERREUR_QUANTITÉ_DURÉE": "Cette durée est incorrecte.",
	"ERREUR_QUALITÉ_DURÉE": "Cette durée est incorrecte.",

	"ERREUR_ORGANISATION": "Cette organistion est incorrecte.",
	"ERREUR_ORGANISATION_SERVICE": "Cette organisation ne correspond pas au service indiqué.",
	"ERREUR_ORGANISATION_INEXISTANTE": "Cette organisation n’existe pas.",
	"ERREUR_SERVICE": "Ce service est incorrect.",
	"ERREUR_SERVICE_INEXISTANT": "Ce service n’existe pas.",
	"ERREUR_OFFRE_INEXISTANTE": "Cette offre n’existe pas.",
	"ERREUR_FORMATION_INEXISTANTE": "Cette formation n’existe pas.",
	"ERREUR_ÉTABLISSEMENT_INEXISTANT": "Cet établissement n’existe pas.",
	"ERREUR_INSTITUTION_INEXISTANTE": "Cette institution n’existe pas.",

	"ERREUR_INCONNUE": "Une erreur inconnue est survenue.",

	// Codes d’erreur particuliers
	"ERREUR_AUTORISATION_TRAITEMENT_DONNÉES_PERSONNELLES": "Vous devez autoriser le traitement de vos données personnelles.",
	"ERREUR_AUTORISATION_TRAITEMENT_DONNÉES_PROFESSIONNELLES": "Vous devez autoriser le traitement de vos données professionnelles.",
	"ERREUR_NOM_UTILISATEUR_EXISTANT": "Ce nom d’utilisateur est déjà pris.",
	"ERREUR_MOT_DE_PASSE": "Les deux mots de passe indiqués ne correspondent pas.",
	"ERREUR_TYPE_ADMINISTRATEUR": "Vous ne pouvez pas vous inscrire comme administrateur.",
	"ERREUR_FICHIER": "Une erreur est survenue avec le(s) fichier(s) envoyé(s). Vérifiez qu’il ne soit pas trop lourd.",
	"EBADCSRFTOKEN": "Jeton incorrect ou manquant.",
	"ETIMEDOUT": "La requête a expiré.",

	// Codes d’erreur HTTP classiques
	"Bad Request": "Mauvaise requête",
	"Payment Required": "Paiement requis",
	"Unauthorized": "Vous devez être connecté",
	"Forbidden": "Page interdite d’accès",
	"Not Found": "Cette page n’existe pas",
	"Method Not Allowed": "Méthode non autorisée",
	"Not Acceptable": "Requête inacceptable",
	"Proxy Authentication Required": "Authentification par proxy requise",
	"Request Timeout": "Requête expirée",
	"Conflict": "Requête conflictuelle",
	"Gone": "Ressource déplacée",
	"Length Required": "Longueur de requête requise",
	"Precondition Failed": "Condition manquante",
	"Request Entity Too Large": "Requête trop lourde",
	"Request-URI Too Long": "Requête trop longue",
	"Unsupported Media Type": "Type de média non supporté",
	"Requested Range Unsatisfiable": "Intervalle incorrect",
	"Expectation Failed": "Comportement inattendu",
	"I’m a teapot": "Je suis une théière",
	"Misdirected Request": "Requête mal dirigée",
	"Upgrade Required": "Protocole non supporté",
	"Precondition Required": "Requête inconditionnelle",
	"Too Many Requests": "Excès de quota",
	"Request Header Fields Too Large": "En‐têtes trop grands",
	"Unavailable For Legal Reasons": "Requête illégale",

	"Internal Server Error": "Erreur interne",
	"Not Implemented": "Fonctionnalité inexistante",
	"Bad Gateway": "Route incorrecte",
	"Service Unavailable": "Service indisponible",
	"Gateway Timeout": "Requête expirée",
	"HTTP Version Not Supported": "Protocole non supporté",
	"Variant Also Negotiates": "Erreur de négociation",
	"Bandwidth Limit Exceeded": "Excès de quota",
	"Not Extended": "Requête incorrecte",
	"Network Authentication Required": "Authentification requise",
}
