
module.exports = {
	// Europe
	"AL": { "nom": "Albanie", "continent": "Europe", },
	"DE": { "nom": "Allemagne", "continent": "Europe", },
	"AD": { "nom": "Andorre", "continent": "Europe", },
	"AT": { "nom": "Autriche", "continent": "Europe", },
	"BE": { "nom": "Belgique", "continent": "Europe", },
	"BY": { "nom": "Biélorussie", "continent": "Europe", },
	"BA": { "nom": "Bosnie‐Herzégovine", "continent": "Europe", },
	"BG": { "nom": "Bulgarie", "continent": "Europe", },
	"HR": { "nom": "Croatie", "continent": "Europe", },
	"DK": { "nom": "Danemark (Royaume de)", "continent": "Europe", },
	"ES": { "nom": "Espagne", "continent": "Europe", },
	"EE": { "nom": "Estonie", "continent": "Europe", },
	"FI": { "nom": "Finlande", "continent": "Europe", },
	"FR": { "nom": "France", "continent": "Europe", },
	"GR": { "nom": "Grèce", "continent": "Europe", },
	"HU": { "nom": "Hongrie", "continent": "Europe", },
	"IE": { "nom": "Irlande", "continent": "Europe", },
	"IS": { "nom": "Islande", "continent": "Europe", },
	"IT": { "nom": "Italie", "continent": "Europe", },
	"LV": { "nom": "Lettonie", "continent": "Europe", },
	"LT": { "nom": "Lituanie", "continent": "Europe", },
	"LI": { "nom": "Liechstenstein", "continent": "Europe", },
	"LU": { "nom": "Luxembourg", "continent": "Europe", },
	"MK": { "nom": "Macédoine du Nord", "continent": "Europe", },
	"MT": { "nom": "Malte", "continent": "Europe", },
	"MD": { "nom": "Moldavie", "continent": "Europe", },
	"MC": { "nom": "Monaco", "continent": "Europe", },
	"ME": { "nom": "Monténégro", "continent": "Europe", },
	"NO": { "nom": "Norvège", "continent": "Europe", },
	"NL": { "nom": "Pays‐Bas", "continent": "Europe", },
	"PL": { "nom": "Pologne", "continent": "Europe", },
	"PT": { "nom": "Portugal", "continent": "Europe", },
	"RO": { "nom": "Roumanie", "continent": "Europe", },
	"GB": { "nom": "Royaume‐Uni (de Grande‐Bretagne et d’Irlande du Nord)", "continent": "Europe", },
	"SM": { "nom": "Saint‐Marin", "continent": "Europe", },
	"RS": { "nom": "Serbie", "continent": "Europe", },
	"SK": { "nom": "Slovaquie", "continent": "Europe", },
	"SI": { "nom": "Slovénie", "continent": "Europe", },
	"SE": { "nom": "Suède", "continent": "Europe", },
	"CH": { "nom": "Suisse", "continent": "Europe", },
	"CZ": { "nom": "Tchéquie", "continent": "Europe", },
	"UA": { "nom": "Ukraine", "continent": "Europe", },
	"VA": { "nom": "Vatican (Saint‐Siège)", "continent": "Europe", },

	// Amérique
	"AG": { "nom": "Antigua‐et‐Barbuda", "continent": "Amérique", },
	"AR": { "nom": "Argentine", "continent": "Amérique", },
	"BS": { "nom": "Bahamas (les)", "continent": "Amérique", },
	"BB": { "nom": "Barbade (la)", "continent": "Amérique", },
	"BZ": { "nom": "Bélize", "continent": "Amérique", },
	"BO": { "nom": "Bolivie", "continent": "Amérique", },
	"BR": { "nom": "Brésil", "continent": "Amérique", },
	"CA": { "nom": "Canada", "continent": "Amérique", },
	"CL": { "nom": "Chili", "continent": "Amérique", },
	"CO": { "nom": "Colombie", "continent": "Amérique", },
	"CR": { "nom": "Costa Rica", "continent": "Amérique", },
	"CU": { "nom": "Cuba", "continent": "Amérique", },
	"DM": { "nom": "Dominique", "continent": "Amérique", },
	"EC": { "nom": "Équateur", "continent": "Amérique", },
	"US": { "nom": "États‐Unis d’Amérique (les)", "continent": "Amérique", },
	"GD": { "nom": "Grenade", "continent": "Amérique", },
	"GT": { "nom": "Guatemala", "continent": "Amérique", },
	"GY": { "nom": "Guyana", "continent": "Amérique", },
	"HT": { "nom": "Haïti", "continent": "Amérique", },
	"HN": { "nom": "Honduras", "continent": "Amérique", },
	"JM": { "nom": "Jamaïque", "continent": "Amérique", },
	"MX": { "nom": "Mexique", "continent": "Amérique", },
	"NI": { "nom": "Nicaragua", "continent": "Amérique", },
	"PA": { "nom": "Panama", "continent": "Amérique", },
	"PY": { "nom": "Paraguay", "continent": "Amérique", },
	"PE": { "nom": "Pérou", "continent": "Amérique", },
	"DO": { "nom": "République dominicaine", "continent": "Amérique", },
	"KN": { "nom": "Saint‐Christophe‐et‐Niévès (Saint‐Kitts‐et‐Nevis)", "continent": "Amérique", },
	"VC": { "nom": "Saint‐Vicent‐et‐les‐Grenadines", "continent": "Amérique", },
	"LC": { "nom": "Sainte‐Lucie", "continent": "Amérique", },
	"SV": { "nom": "Salvador", "continent": "Amérique", },
	"SR": { "nom": "Suriname", "continent": "Amérique", },
	"TT": { "nom": "Trinité‐et‐Tobago", "continent": "Amérique", },
	"UY": { "nom": "Uruguay", "continent": "Amérique", },
	"VE": { "nom": "Venezuela", "continent": "Amérique", },

	// Moyen‐Orient
	"SA": { "nom": "Arabie saoudite", "continent": "Moyen‐Orient", },
	"BH": { "nom": "Bahreïn", "continent": "Moyen‐Orient", },
	"CY": { "nom": "Chypre", "continent": "Moyen‐Orient", },
	"EG": { "nom": "Égypte", "continent": "Moyen‐Orient", },
	"AE": { "nom": "Émirats arabes unis (les)", "continent": "Moyen‐Orient", },
	"IQ": { "nom": "Irak", "continent": "Moyen‐Orient", },
	"IR": { "nom": "Iran", "continent": "Moyen‐Orient", },
	"IL": { "nom": "Israël", "continent": "Moyen‐Orient", },
	"JO": { "nom": "Jordanie", "continent": "Moyen‐Orient", },
	"KW": { "nom": "Koweït", "continent": "Moyen‐Orient", },
	"LB": { "nom": "Liban", "continent": "Moyen‐Orient", },
	"OM": { "nom": "Oman (sultanat d’)", "continent": "Moyen‐Orient", },
	"PS": { "nom": "Palestine", "continent": "Moyen‐Orient", },
	"QA": { "nom": "Qatar", "continent": "Moyen‐Orient", },
	"SY": { "nom": "Syrie", "continent": "Moyen‐Orient", },
	"TR": { "nom": "Turquie", "continent": "Moyen‐Orient", },
	"YE": { "nom": "Yémen", "continent": "Moyen‐Orient", },

	// Asie
	"AF": { "nom": "Afghanistan", "continent": "Asie", },
	"AZ": { "nom": "Azerbaïdjan", "continent": "Asie", },
	"AM": { "nom": "Arménie", "continent": "Asie", },
	"BT": { "nom": "Bhoutan", "continent": "Asie", },
	"MM": { "nom": "Birmanie (Myanmar)", "continent": "Asie", },
	"BN": { "nom": "Brunei", "continent": "Asie", },
	"CN": { "nom": "Chine", "continent": "Asie", },
	"KP": { "nom": "Corée du Nord", "continent": "Asie", },
	"KR": { "nom": "Corée du Sud", "continent": "Asie", },
	"GE": { "nom": "Géorgie", "continent": "Asie", },
	"IN": { "nom": "Inde", "continent": "Asie", },
	"ID": { "nom": "Indonésie", "continent": "Asie", },
	"JP": { "nom": "Japon", "continent": "Asie", },
	"KZ": { "nom": "Kazakhstan", "continent": "Asie", },
	"KG": { "nom": "Kirghizistan", "continent": "Asie", },
	"LA": { "nom": "Laos", "continent": "Asie", },
	"MY": { "nom": "Malaisie", "continent": "Asie", },
	"MV": { "nom": "Maldives (les)", "continent": "Asie", },
	"NP": { "nom": "Népal", "continent": "Asie", },
	"UZ": { "nom": "Ouzbékistan", "continent": "Asie", },
	"PK": { "nom": "Pakistan", "continent": "Asie", },
	"PH": { "nom": "Philippines (les)", "continent": "Asie", },
	"RU": { "nom": "Russie", "continent": "Asie", },
	"SG": { "nom": "Singapour", "continent": "Asie", },
	"LK": { "nom": "Sri Lanka", "continent": "Asie", },
	"TJ": { "nom": "Tadjikistan", "continent": "Asie", },
	"TH": { "nom": "Thaïlande", "continent": "Asie", },
	"TL": { "nom": "Timor‐Oriental (Leste)", "continent": "Asie", },
	"TM": { "nom": "Turkménistan", "continent": "Asie", },
	"VN": { "nom": "Viêt Nam", "continent": "Asie", },

	// Afrique
	"ZA": { "nom": "Afrique du Sud", "continent": "Afrique", },
	"DZ": { "nom": "Algérie", "continent": "Afrique", },
	"AO": { "nom": "Angola", "continent": "Afrique", },
	"BJ": { "nom": "Bénin", "continent": "Afrique", },
	"BW": { "nom": "Botswana", "continent": "Afrique", },
	"BF": { "nom": "Burkina Faso", "continent": "Afrique", },
	"BI": { "nom": "Burundi", "continent": "Afrique", },
	"KH": { "nom": "Cambodge", "continent": "Afrique", },
	"CM": { "nom": "Cameroun", "continent": "Afrique", },
	"CV": { "nom": "Cap‐Vert (iles)", "continent": "Afrique", },
	"CF": { "nom": "Centrafrique", "continent": "Afrique", },
	"KM": { "nom": "Comores (les)", "continent": "Afrique", },
	"CG": { "nom": "Congo (Brazzaville)", "continent": "Afrique", },
	"CD": { "nom": "Congo (Kinshasa)", "continent": "Afrique", },
	"CI": { "nom": "Côte d’Ivoire", "continent": "Afrique", },
	"DJ": { "nom": "Djibouti", "continent": "Afrique", },
	"ET": { "nom": "Éthiopie", "continent": "Afrique", },
	"ER": { "nom": "Érythrée", "continent": "Afrique", },
	"SZ": { "nom": "Eswatini (Swaziland)", "continent": "Afrique", },
	"GA": { "nom": "Gabon", "continent": "Afrique", },
	"GM": { "nom": "Gambie", "continent": "Afrique", },
	"GH": { "nom": "Ghana", "continent": "Afrique", },
	"GN": { "nom": "Guinée", "continent": "Afrique", },
	"GW": { "nom": "Guinée‐Bissau", "continent": "Afrique", },
	"GQ": { "nom": "Guinée équatoriale", "continent": "Afrique", },
	"KE": { "nom": "Kenya", "continent": "Afrique", },
	"LR": { "nom": "Libéria", "continent": "Afrique", },
	"LY": { "nom": "Lybie", "continent": "Afrique", },
	"MG": { "nom": "Madagascar", "continent": "Afrique", },
	"MW": { "nom": "Malawi", "continent": "Afrique", },
	"ML": { "nom": "Mali", "continent": "Afrique", },
	"MA": { "nom": "Maroc", "continent": "Afrique", },
	"MU": { "nom": "Maurice (iles)", "continent": "Afrique", },
	"MR": { "nom": "Mauritanie", "continent": "Afrique", },
	"MZ": { "nom": "Mozambique", "continent": "Afrique", },
	"NA": { "nom": "Namibie", "continent": "Afrique", },
	"NE": { "nom": "Niger", "continent": "Afrique", },
	"NG": { "nom": "Nigéria", "continent": "Afrique", },
	"UG": { "nom": "Ouganda", "continent": "Afrique", },
	"RW": { "nom": "Rwanda", "continent": "Afrique", },
	"ST": { "nom": "Sao Tomé‐et‐Principe", "continent": "Afrique", },
	"SN": { "nom": "Sénégal", "continent": "Afrique", },
	"SC": { "nom": "Seychelles (les)", "continent": "Afrique", },
	"SL": { "nom": "Sierra Leone", "continent": "Afrique", },
	"SO": { "nom": "Somalie", "continent": "Afrique", },
	"SD": { "nom": "Soudan", "continent": "Afrique", },
	"SS": { "nom": "Soudan du Sud", "continent": "Afrique", },
	"TZ": { "nom": "Tanzanie", "continent": "Afrique", },
	"TD": { "nom": "Tchad", "continent": "Afrique", },
	"TG": { "nom": "Togo", "continent": "Afrique", },
	"TN": { "nom": "Tunisie", "continent": "Afrique", },
	"ZM": { "nom": "Zambie", "continent": "Afrique", },
	"ZW": { "nom": "Zimbabwe", "continent": "Afrique", },

	// Océanie
	"AU": { "nom": "Australie", "continent": "Océanie", },
	"CK": { "nom": "Cook (iles)", "continent": "Océanie", },
	"FJ": { "nom": "Fidji (iles)", "continent": "Océanie", },
	"KI": { "nom": "Kiribati", "continent": "Océanie", },
	"MH": { "nom": "Marshall (iles)", "continent": "Océanie", },
	"FM": { "nom": "Micronésie", "continent": "Océanie", },
	"NR": { "nom": "Nauru", "continent": "Océanie", },
	"NU": { "nom": "Nioué (Niue)", "continent": "Océanie", },
	"NZ": { "nom": "Nouvelle‐Zélande", "continent": "Océanie", },
	"PW": { "nom": "Palaos (les)", "continent": "Océanie", },
	"PG": { "nom": "Papouasie‐Nouvelle‐Guinée", "continent": "Océanie", },
	"SB": { "nom": "Salomon (iles)", "continent": "Océanie", },
	"WS": { "nom": "Saoma", "continent": "Océanie", },
	"TO": { "nom": "Tonga (iles)", "continent": "Océanie", },
	"TV": { "nom": "Tuvalu (les)", "continent": "Océanie", },
	"VU": { "nom": "Vanuatu", "continent": "Océanie", },

	"AUTRE": { "nom": "Autre", "continent": "Autres", },
}
