
module.exports = {
	"aéronautique": "Aéronautique et espace",
	"agriculture": "Agriculture et agroalimentaire",
	"artisanat": "Artisanat",
	"audiovisuel": "Audiovisuel et cinéma",
	"automobile": "Automobile",
	"banques": "Banques et assurances",
	"btp": "Bâtiments et travaux publics",
	"biochimie": "Biologie, chimie et parachimie",
	"commerce": "Commerce et distribution",
	"communication": "Communication",
	"comptabilité": "Comptabilité, gestion et audit",
	"édition": "Édition et imprimerie",
	"énergie": "Énergie",
	"enseignement": "Enseignement",
	"ferroviaire": "Ferroviaire",
	"public": "Fonction publique",
	"hôtel": "Hôtellerie et restauration",
	"industrie": "Industrie",
	"information": "Journalisme",
	"immobilier": "Immobilier",
	"tic": "Informatique et télécoms",
	"médical": "Médical et paramédical",
	"publicité": "Publicité et mercatique",
	"recherche": "Recherche",
	"spectacle": "Spectacle",
	"ressources": "Ressources humaines",
	"textile": "Textiles",
	"tourisme": "Tourisme",
	"transport": "Transport et logistique",
	"autre": "Autre",
}
