
module.exports = {
	"nomUtilisateur": "Nom d’utilisateur…",
	"motDePasse": "Mot de passe…",
	"changementMotDePasse": "Votre nouveau mot de passe…",
	"confirmationMotDePasse": "Répétez votre nouveau mot de passe…",
	"prénom": "Votre prénom…",
	"nom": "Nom…",
	"nomPatronymique": "Votre nom patronymique…",
	"nomMarital": "Votre nom marital…",
	"dateNaissance": "Votre date de naissance…",
	"adresseMél": "Votre adresse mél…",
	"choixStatut": "Choisissez votre statut…",
	"raisonSociale": "Raison sociale…",
	"effectif": "Effectif…",
	"ville": "Ville…",
	"codePostal": "Code postal…",
	"choixPays": "Choisissez votre pays…",
	"recherche": "Recherche…",
	"secteurActivité": "Secteur d’activité…",
	"lienSitePersonnel": "Lien vers votre site personnel…",
	"lienSiteProfessionnel": "Lien vers le site professionnel…",
	"lienLinkedIn": "Lien vers votre page LinkedIn…",
	"lienViadeo": "Lien vers votre page Viadeo…",
	"numéroTéléphone": "Votre numéro de téléphone…",
	"posteActuel": "Votre poste actuel…",
	"intituléCourt": "L’intitulé court de la formation…",
	"intituléComplet": "L’intitulé complet de la formation…",
	"intituléOffre": "L’intitulé de l’offre…",
	"périodeEmploi": "Période de disponibilité…",
	"domaines": "Vos domaines d’intérêt…",
	"périodeValidité": "Période de validité…",
	"CVDéposé": "CV déposé",
	"CVManquant": "Aucun CV n’a été déposé",
	"fichierDéposé": "Fichier déposé",
	"fichierManquant": "Aucun fichier n’a été déposé",
	"saisieRecherche": "Saisissez un texte pour chercher…",
	"motif": "Motif…",
	"adresse": "Adresse…",
	"description": "Description…",
}
