
module.exports = {
	"connexion": "Connexion",
	"inscription": "Inscription",
	"enregistrement": "Enregistrement",
	"inscriptionOrganisation": "Inscription d’une organisation",
	"inscriptionService": "Inscription d’un service",
	"enregistrementOffre": "Enregistrement d’une offre",
	"inscriptionFormation": "Inscription d’une formation",
	"inscriptionÉtablissement": "Inscription d’un établissement",
	"inscriptionInstitution": "Inscription d’une institution",

	"organisationManquante": "Organisation manquante",
	"serviceManquant": "Service manquant",
	"formationManquante": "Formation manquante",
	"établissementManquant": "Établissement manquant",
	"institutionManquante": "Mon institution est manquante",

	"nomUtilisateur": "Nom d’utilisateur",
	"motDePasse": "Mot de passe",
	"changementMotDePasse": "Votre nouveau mot de passe",
	"confirmationMotDePasse": "Confirmation de votre nouveau mot de passe",
	"prénom": "Prénom",
	"nom": "Nom",
	"nomPatronymique": "Nom patronymique",
	"nomMarital": "Nom marital",
	"nomUsuel": "Nom usuel",
	"civilité": "Civilité",
	"civilitéFemme": "Madame",
	"civilitéHomme": "Monsieur",
	"dateNaissance": "Date de naissance",
	"lienSitePersonnel": "Lien vers votre site personnel",
	"lienSiteProfessionnel": "Lien vers le site professionnel",
	"lienLinkedIn": "Lien vers votre page LinkedIn",
	"lienViadeo": "Lien vers votre page Viadeo",
	"adresseMél": "Adresse mél (non public)",
	"numéroTéléphone": "Numéro de téléphone (non public)",
	"statutPersonnel": "Je suis…",
	"autorisationTraitementDonnéesPersonnelles": "J’autorise le traitement de mes données personnelles",
	"autorisationTraitementDonnéesProfessionnelles": "J’autorise le traitement de mes données professionnelles",

	"raisonSociale": "Raison sociale",
	"effectif": "Effectif",
	"siège": "Siège",
	"ville": "Ville",
	"villeSiègeSocial": "Ville du siège social",
	"codePostal": "Code postal",
	"codePostalSiègeSocial": "Code postal du siège social",
	"localisation": "Localisation",
	"siègeSocial": "Siège social",
	"pays": "Pays",
	"paysSiègeSocial": "Pays du siège social",

	"recherche": "Rechercher",
	"nonRecherche": "Je ne recherche pas un emploi",
	"périodeEmploi": "Période de disponibilité",
	"domaines": "Domaines",
	"vosDomaines": "Vos domaines d’intérêt",
	"périodeFormation": "Période de formation",
	"filtrage": "Filtrer",
	"statut": "Statut",
	"formation": "Formation",
	"promotion": "Promotion",
	"tri": "Tri",
	"triAlphabétique": "Alphabétique",
	"triAntiAlphabétique": "Anti‐alphabétique",
	"secteurActivité": "Secteur d’activité",
	"proposeOffres": "Propose des offres",
	"typeEmploi": "Type d’emploi",
	"posteActuel": "Poste actuel",
	"intitulé": "Intitulé",
	"choixImage": "Choisir une image…",
	"CV": "Votre Curriculum Vitae",
	"fichier": "Fichier joint",
	"choixFichier": "Choisir un fichier… (PDF)",
	"intervalleValidité": "Période de validité",
	"durée": "Durée",
	"intituléCourt": "Ititulé court de la formation (par. ex. « DUT Informatique »)",
	"intituléComplet": "Intitulé complet de la formation (par. ex. « Diplôme Universitaire de Technologie en Informatique »)",
	"ajoutFormation": "Ajouter une formation",
	"motif": "Motif",
	"adresse": "Adresse",
	"description": "Description",

	"organisation": "Organisation",
	"votreOrganisation": "Votre organisation",
	"service": "Service",
	"votreService": "Votre service",
	"établissement": "Établissement",
	"institution": "Institution",

	"alerteInscriptionMembre": [ "Votre compte sera mis en attente de validation.", "Un mot de passe vous sera fourni, vous devrez le changer.", ],

	"nulRésultat": "Nul résultat.",
}
